### ISSUE TITLE
A question about kl_nms

### ISSUE THREAD

**Issue by lalalafloat** [cxliu0/KL-Loss-pytorch#2]
Thank you for using the implementation of PyTorch for this article, I have a small question, should [bbox_var](https://github.com/cxliu0/KL-Loss-pytorch/blob/1acdce6753559915edb9615faa0fa8768c397bea/mmdet/models/roi_heads/standard_roi_head_kl.py#LL345C6-L345C6) in this place be changed to 'bbox_var[i]'?

**Comment by cxliu0** [comment]
We use ```batch_size=1``` during inference. In this case,  it is not necessary to use ```bbox_var[i]```, because we do not split ```bbox_var``` based on [```num_proposals_per_img``` ](https://github.com/cxliu0/KL-Loss-pytorch/blob/1acdce6753559915edb9615faa0fa8768c397bea/mmdet/models/roi_heads/standard_roi_head_kl.py#L325). 

However, if you wish to test with ```batch_size>1``` , you may need to modify ```bbox_var``` (similar to [bbox_pred](https://github.com/cxliu0/KL-Loss-pytorch/blob/1acdce6753559915edb9615faa0fa8768c397bea/mmdet/models/roi_heads/standard_roi_head_kl.py#L329)) and use ```bbox_var[i]```.

**Comment by lalalafloat** [comment]
Okay, I understand, thank you for your rapid and effective reply.
